/*
* CODE GENERATED AUTOMATICALLY GENERATED BY github.com/quii/modest-mock
* THIS FILE SHOULD NOT BE EDITED BY HAND. UNLESS YOU ENJOY SAD TIMES.
*/

package example

import "fmt"

type BankMock struct {
	Calls struct {
		CheckPin []BankMock_CheckPinArgs

		Deposit []BankMock_DepositArgs

		Withdraw []BankMock_WithdrawArgs
	}

	Returns struct {
		CheckPin map[BankMock_CheckPinArgs]BankMock_CheckPinReturns

		Deposit map[BankMock_DepositArgs]BankMock_DepositReturns

		Withdraw map[BankMock_WithdrawArgs]BankMock_WithdrawReturns
	}
}

func (b *BankMock) CheckPin(cardNumber int, pin int) (accountNumber int, success bool) {
	call := BankMock_CheckPinArgs{cardNumber, pin}
	b.Calls.CheckPin = append(b.Calls.CheckPin, call)

	if vals, exists := b.Returns.CheckPin[call]; exists {
		return vals.accountNumber, vals.success
	}

	panic(fmt.Sprintf("no return values found for args %+v, ive got %+v", call, b.Returns.CheckPin))

}

func (b *BankMock) Deposit(accountNumber string, amount int) (newBalance int, err error) {
	call := BankMock_DepositArgs{accountNumber, amount}
	b.Calls.Deposit = append(b.Calls.Deposit, call)

	if vals, exists := b.Returns.Deposit[call]; exists {
		return vals.newBalance, vals.err
	}

	panic(fmt.Sprintf("no return values found for args %+v, ive got %+v", call, b.Returns.Deposit))

}

func (b *BankMock) Withdraw(accountNumber string, amount int) (newBalance int, err error) {
	call := BankMock_WithdrawArgs{accountNumber, amount}
	b.Calls.Withdraw = append(b.Calls.Withdraw, call)

	if vals, exists := b.Returns.Withdraw[call]; exists {
		return vals.newBalance, vals.err
	}

	panic(fmt.Sprintf("no return values found for args %+v, ive got %+v", call, b.Returns.Withdraw))

}

type BankMock_CheckPinArgs struct {
	cardNumber int
	pin        int
}

type BankMock_CheckPinReturns struct {
	accountNumber int
	success       bool
}

type BankMock_DepositArgs struct {
	accountNumber string
	amount        int
}

type BankMock_DepositReturns struct {
	newBalance int
	err        error
}

type BankMock_WithdrawArgs struct {
	accountNumber string
	amount        int
}

type BankMock_WithdrawReturns struct {
	newBalance int
	err        error
}
